apiVersion: v1
kind: ConfigMap
metadata:
  name: common-environment-variables
data:
  JAVA_OPTS: "-Xms256m -Xmx512m"
  SPRING_CLOUD_CONFIG_URI: "http://cloud-config:9296"
  EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT: myzone
  EUREKA_CLIENT_FETCH_REGISTRY: "true"
  EUREKA_CLIENT_HEALTHCHECK_ENABLED: "true"
  EUREKA_CLIENT_REGION: default
  EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://service-discovery:8761/eureka"
  EUREKA_CLIENT_SERVICEURL_MYZONE: "http://service-discovery:8761/eureka"
  EUREKA_INSTANCE_LEASE_EXPIRATION_DURATION_IN_SECONDS: "30"
  EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS: "10"
  EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
  SPRING_PROFILES_ACTIVE: ${ENV}
  SPRING_ZIPKIN_BASE_URL: "http://zipkin:9411"
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-service:3306/ecommerce_stage_db"
  SPRING_DATASOURCE_USERNAME: "root"